spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/token
    username: tokenuser2
    password: tokenuser2
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  security:
    oauth2:
      client:
        registration:
          # 'kakao'? ??? ID??, /login/oauth2/code/kakao URL? 'kakao' ??? ?????.
          kakao:
            client-id: 739ade89d5b44fcc3caf0b604d82f0f9 # ??? ??? ??? REST API ?
            client-secret: ${KAKAO_CLIENT_SECRET} # ??? ??? ???? ???? Client Secret
            client-authentication-method: client_secret_post # ?? client_secret_basic (???? ???? ?? ??)
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/login/oauth2/code/kakao} # ??? ??? ??? ??? Redirect URI
            # scope: profile_nickname,profile_image,account_email # ??? ?? (??? ??)
            scope: profile_nickname # ???? ??? ?? (??? ??)
            client-name: Kakao # ??? ???? ??? ?? (?? ??)
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # ????? ??? ??? ???? ?? (?? 'id' ?? 'sub')